const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');if(toggle&&nav){toggle.addEventListener('click',()=>{nav.classList.toggle('is-open');toggle.setAttribute('aria-expanded',nav.classList.contains('is-open'));});}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(!lines.length)return[];const headers=lines[0].split(';').map(s=>s.trim());return lines.slice(1).filter(Boolean).map(line=>{const vals=line.split(';');return Object.fromEntries(headers.map((h,i)=>[h,(vals[i]||'').trim()]));});}
const palette=['#edf3e2','#d6e9c0','#b8db94','#8ec14f','#5c9937','#2d6f39'];let communeData={};let currentMetric='nb_especes';let mapLayers={};let leafletMap=null;
function valueOrDash(v){return v===''||v==null?'—':v;}
function normalizeName(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,"'").toLowerCase();}
function selectCommune(id){Object.entries(mapLayers).forEach(([key,layer])=>{layer.setStyle({weight:key===id?4:2,color:key===id?'#2f5148':'#fff'});});const d=communeData[id];if(!d)return;document.querySelector('#map-name').textContent=d.commune;document.querySelector('#map-date').textContent=d.date_maj?`Données mises à jour le ${d.date_maj}`:'Date de mise à jour non renseignée';document.querySelector('#map-species').textContent=valueOrDash(d.nb_especes);document.querySelector('#map-roosts').textContent=valueOrDash(d.nb_gites);document.querySelector('#map-bats').textContent=valueOrDash(d.nb_individus);document.querySelector('#map-buildings').textContent=valueOrDash(d.batiments_prospectes);document.querySelector('#map-caves').textContent=valueOrDash(d.cavites_prospectees);document.querySelector('#map-nights').textContent=valueOrDash(d.nuits_acoustiques);}
function metricColor(metric,value){if(value===''||value==null)return '#e5e5df';const vals=Object.values(communeData).map(d=>Number(d[metric])).filter(v=>Number.isFinite(v)&&v>=0);const max=vals.length?Math.max(...vals):0;const v=Number(value)||0;const idx=max?Math.min(palette.length-1,Math.floor((v/max)*(palette.length-1))):0;return palette[idx];}
function colorMap(metric){currentMetric=metric;Object.entries(mapLayers).forEach(([id,layer])=>{const d=communeData[id];layer.setStyle({fillColor:metricColor(metric,d?d[metric]:''),fillOpacity:.9});});const legend=document.querySelector('#map-legend');if(legend){legend.innerHTML=`<span><i style="background:#e5e5df"></i>Aucune donnée saisie</span><span><i style="background:${palette[1]}"></i>Faible</span><span><i style="background:${palette[3]}"></i>Moyen</span><span><i style="background:${palette[5]}"></i>Élevé</span>`;}}
async function fetchCommuneGeometry(row){const params=new URLSearchParams({nom:row.commune,codeDepartement:row.departement||'34',format:'geojson',geometry:'contour'});const res=await fetch(`https://geo.api.gouv.fr/communes?${params.toString()}`);if(!res.ok)throw new Error(`Contour introuvable pour ${row.commune}`);const geo=await res.json();if(!geo.features?.length)throw new Error(`Contour introuvable pour ${row.commune}`);const exact=geo.features.find(f=>normalizeName(f.properties.nom)===normalizeName(row.commune));return exact||geo.features[0];}
async function initMap(){const target=document.querySelector('#territory-map');if(!target||typeof L==='undefined')return;try{const rows=parseCSV(await (await fetch('data/donnees-communes.csv',{cache:'no-store'})).text());rows.forEach(d=>communeData[d.id]=d);leafletMap=L.map(target,{zoomControl:true,attributionControl:false,scrollWheelZoom:false,preferCanvas:false});leafletMap.createPane('labels');leafletMap.getPane('labels').style.zIndex=650;leafletMap.getPane('labels').style.pointerEvents='none';const group=L.featureGroup().addTo(leafletMap);const results=await Promise.allSettled(rows.map(async row=>({row,feature:await fetchCommuneGeometry(row)})));results.forEach(result=>{if(result.status!=='fulfilled'){console.warn(result.reason);return;}const {row,feature}=result.value;const layer=L.geoJSON(feature,{style:{color:'#fff',weight:2,fillColor:metricColor(currentMetric,row[currentMetric]),fillOpacity:.9},onEachFeature:(_,l)=>{l.on({click:()=>selectCommune(row.id),mouseover:()=>l.setStyle({weight:3,color:'#2f5148'}),mouseout:()=>l.setStyle({weight:2,color:'#fff'})});}}).addTo(group);mapLayers[row.id]=layer;const center=layer.getBounds().getCenter();L.marker(center,{pane:'labels',interactive:false,icon:L.divIcon({className:'commune-map-label',html:`<span>${row.commune}</span>`,iconSize:null})}).addTo(leafletMap);});if(group.getLayers().length){leafletMap.fitBounds(group.getBounds(),{padding:[24,24]});}else{target.innerHTML='<p class="map-load-error">Impossible de charger les contours communaux.</p>';}document.querySelectorAll('.map-filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.map-filter').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');colorMap(btn.dataset.metric);}));colorMap(currentMetric);const dates=rows.map(r=>r.date_maj).filter(Boolean).sort();if(dates.length)document.querySelector('#global-update').textContent=`Dernière mise à jour : ${dates.at(-1)}`;}catch(e){console.error(e);target.innerHTML='<p class="map-load-error">La carte n’a pas pu être chargée. Rechargez la page dans quelques instants.</p>';}}
async function initSpecies(){const grid=document.querySelector('#species-grid');if(!grid)return;try{const rows=await (await fetch('data/especes.json',{cache:'no-store'})).json();grid.innerHTML=rows.map(s=>`<article class="species-card"><div class="species-photo-placeholder">Photo à ajouter</div><div class="species-copy"><h3><a href="${s.lien_sfepm}" target="_blank" rel="noopener">${s.nom}</a></h3><p><em>${s.scientifique}</em></p><a class="species-link" href="${s.lien_sfepm}" target="_blank" rel="noopener">Voir la monographie SFEPM →</a></div></article>`).join('');}catch(e){console.error(e);}}
initMap();initSpecies();
