const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.main-nav');
if(toggle&&nav){toggle.addEventListener('click',()=>{nav.classList.toggle('is-open');toggle.setAttribute('aria-expanded',nav.classList.contains('is-open'));});}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(!lines.length)return[];const headers=lines[0].split(';').map(s=>s.trim());return lines.slice(1).filter(Boolean).map(line=>{const vals=line.split(';');return Object.fromEntries(headers.map((h,i)=>[h,(vals[i]||'').trim()]));});}
let communeData={};let selectedCode=null;
function valueOrDash(v){return v===''||v==null?'—':v;}
function selectCommune(code){selectedCode=code;document.querySelectorAll('.commune-shape').forEach(el=>el.classList.toggle('is-selected',el.dataset.code===code));document.querySelectorAll('.commune-label').forEach(el=>el.classList.toggle('is-selected',el.dataset.labelCode===code));const d=communeData[code];if(!d)return;document.querySelector('#map-name').textContent=d.commune;document.querySelector('#map-date').textContent=d.date_maj?`Données mises à jour le ${d.date_maj}`:'Date de mise à jour non renseignée';document.querySelector('#map-species').textContent=valueOrDash(d.nb_especes);document.querySelector('#map-roosts').textContent=valueOrDash(d.nb_gites);document.querySelector('#map-bats').textContent=valueOrDash(d.nb_individus);document.querySelector('#map-buildings').textContent=valueOrDash(d.batiments_prospectes);document.querySelector('#map-caves').textContent=valueOrDash(d.cavites_prospectees);document.querySelector('#map-nights').textContent=valueOrDash(d.nuits_acoustiques);}
async function initMap(){const target=document.querySelector('#territory-map');if(!target)return;try{const [csvText,svgText]=await Promise.all([fetch('data/donnees-communes.csv',{cache:'no-store'}).then(r=>r.text()),fetch('data/communes.svg',{cache:'no-store'}).then(r=>r.text())]);parseCSV(csvText).forEach(d=>communeData[d.code_insee]=d);target.innerHTML=svgText;target.querySelectorAll('.commune-shape').forEach(el=>{const code=el.dataset.code;el.addEventListener('click',()=>selectCommune(code));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectCommune(code);}});el.addEventListener('mouseenter',()=>{target.querySelector(`[data-label-code="${code}"]`)?.classList.add('is-hovered');});el.addEventListener('mouseleave',()=>{target.querySelector(`[data-label-code="${code}"]`)?.classList.remove('is-hovered');});});const dates=Object.values(communeData).map(r=>r.date_maj).filter(Boolean).sort();if(dates.length)document.querySelector('#global-update').textContent=`Dernière mise à jour : ${dates.at(-1)}`;}catch(e){console.error(e);target.innerHTML='<p class="map-load-error">La carte n’a pas pu être chargée.</p>';}}
async function initSpecies(){const grid=document.querySelector('#species-grid');if(!grid)return;try{const rows=await fetch('data/especes.json',{cache:'no-store'}).then(r=>r.json());grid.innerHTML=rows.map(s=>`<article class="species-card"><div class="species-photo-placeholder">Photo à ajouter</div><div class="species-copy"><h3><a href="${s.lien_sfepm}" target="_blank" rel="noopener">${s.nom}</a></h3><p><em>${s.scientifique}</em></p><a class="species-link" href="${s.lien_sfepm}" target="_blank" rel="noopener">Voir la monographie SFEPM →</a></div></article>`).join('');}catch(e){console.error(e);}}
initMap();initSpecies();